### ISSUE TITLE
Problem with multimodules like i.sentinel

### ISSUE THREAD

**Issue by anikaweinmann** [mundialis/actinia-gdi#31]
The endpoint `gdi_processing_async` has a problem with multimodules like i.sentinel.
A multimodule is only written as e.g. i.sentinel in the `/usr/local/grass/modules.xml` by g.extension and not as i.sentinel.download, i.sentinel.import, ... . So `g.search.modules` (https://github.com/mundialis/actinia-gdi/blob/master/actinia_gdi/core/gmodulesGrass.py#L46) returns only i.sentinel and in http://localhost:8088/api/v1/modules only this is listed and not i.sentinel.download, ... . For this reason, i.sentinel.download, ... can not be unsed with the endpoint  `gdi_processing_async`.

**Comment by neteler** [comment]
I have opened an upstream ticket: https://github.com/OSGeo/grass/issues/514

**Comment by neteler** [comment]
It has been fixed upstream in G79 and G78 via https://github.com/OSGeo/grass/pull/582

Does the fix sufficiently address this issue here, @AnikaBettge ?

**Comment by anikaweinmann** [comment]
@neteler yes.
